stages:
  - build
  - deploy

image: node

build:
  tags:
    - shell
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
      - package-lock.json
    expire_in: 1 week

deploy:
  tags:
    - shell
  stage: deploy
  script:
    - node index.js

